rm -rf AndroidStaggerGridLib/bin/* 
rm -rf AndroidStaggerGridLib/.git 
rm -rf HoloAccentLib/bin/* 
rm -rf HoloAccentLib/.git 
rm -rf MenuComponentLib/bin/* 
rm -rf MenuComponentLib/.git 
rm -rf RefreshNowLib/bin/* 
rm -rf RefreshNowLib/.git 
rm -rf SlidingMenuLib/bin/* 
rm -rf SlidingMenuLib/.git 
rm -rf SmoothProgressBarLib/bin/* 
rm -rf SmoothProgressBarLib/.git 
rm -rf ViewPageIndicatorLib/bin/* 
rm -rf ViewPageIndicatorLib/.git 
rm -rf drag-sort-listview-lib/bin/* 
rm -rf drag-sort-listview-lib/.git 
rm -rf google-play-services_lib/bin/* 
rm -rf google-play-services_lib/.git 
rm -rf twidere/bin/* 
rm -rf twidere/.git 
